name: Test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: poetry run pytest --junitxml=junit.xml --cov-branch --cov=ckine --cov-report xml:coverage.xml
